# Generated by Django 4.1 on 2022-09-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='currency',
            field=models.CharField(choices=[('Hryvnya', 'Uah'), ('US Dollar', 'Usd'), ('Euro', 'Eur')], default='Hryvnya', max_length=10),
        ),
    ]
