# Generated by Django 4.1 on 2022-09-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instruction',
            field=models.URLField(default='www.write_something.com'),
        ),
        migrations.AddField(
            model_name='post',
            name='make_responce',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='response',
            field=models.TextField(default='your opinion'),
            preserve_default=False,
        ),
    ]
