# Generated by Django 4.1 on 2022-09-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_instruction_post_make_responce_post_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='instruction',
            new_name='url_instruction',
        ),
    ]
