# Generated by Django 4.1 on 2022-09-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='make_responce',
            new_name='make_response',
        ),
        migrations.AddField(
            model_name='post',
            name='response',
            field=models.TextField(default='write your opinion'),
            preserve_default=False,
        ),
    ]
