# Generated by Django 4.1 on 2022-09-15 12:31

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[(models.CharField(max_length=80), 'Book Name'), (models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN'), 'Isbn'), (models.DateTimeField(), 'Year Of Issue'), (models.CharField(choices=[('українська', 'Ukrainian'), ('англійська', 'English')], default='українська'), 'Book Language'), (models.CharField(choices=[('історична повість', 'Historical Story'), ('роман', 'Novel'), ('фантастика', 'Fantasy'), ('комікси', 'Comics'), ('казки', 'Tales')]), 'Genre'), (models.CharField(choices=shop.models.Author.__str__), 'Author')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.01, max_digits=10)),
                ('currency', models.CharField(default='українська гривня', max_length=10)),
                ('quantity', models.IntegerField()),
                ('booked', models.IntegerField()),
                ('sale', models.BooleanField(default=False)),
            ],
        ),
    ]
