# Generated by Django 4.1 on 2022-09-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_book_book_name_alter_book_shop_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='book_shop',
            name='book',
            field=models.CharField(max_length=80),
        ),
    ]
