# Generated by Django 4.1 on 2022-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_book_shop_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_shop',
            name='currency',
            field=models.CharField(default='українська гривня', max_length=20),
        ),
    ]
