# Generated by Django 4.1 on 2022-10-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_book_shop_url_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
