# Generated by Django 4.1 on 2022-10-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_book_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_shop',
            name='currency',
            field=models.CharField(default='UAH', max_length=20),
        ),
    ]
