# Generated by Django 4.1 on 2022-11-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_book_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('historical', 'Historical'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('comics', 'Comics'), ('tales', 'Tales'), ('poems', 'Poems'), ('prose', 'Prose')], max_length=20),
        ),
    ]
