# Generated by Django 4.1 on 2022-11-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('historical', 'historical'), ('novel', 'novel'), ('fantasy', 'fantasy'), ('comics', 'comics'), ('tales', 'tales'), ('poems', 'poems'), ('prose', 'prose')], max_length=20),
        ),
    ]
