# Generated by Django 4.1 on 2022-11-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_genre_alter_book_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('historical', 'Historical'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('comics', 'Comics'), ('tales', 'Tales'), ('poems', 'Poems'), ('prose', 'Prose')], max_length=20),
        ),
    ]
